# Generated by Django 5.1.7 on 2025-04-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izzytech', '0002_alter_graphicsmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobile')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='software')),
            ],
        ),
        migrations.CreateModel(
            name='WebModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web')),
            ],
        ),
    ]
