# Generated by Django 5.2 on 2025-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izzytech', '0005_coursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='desired_course',
            field=models.CharField(choices=[('option1', 'Option1'), ('option2', 'Option2'), ('option3', 'Option3')], default='option1', max_length=25),
            preserve_default=False,
        ),
    ]
