# Generated by Django 5.2 on 2025-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izzytech', '0006_coursemodel_desired_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='mode_of_study',
            field=models.CharField(choices=[('option1', 'onsite'), ('option2', 'online')], default='online', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='desired_course',
            field=models.CharField(choices=[('option1', 'Web Design'), ('option2', 'Graphics Design'), ('option3', 'Software Development'), ('option4', 'Mobile App Development')], max_length=25),
        ),
    ]
